### PR TITLE
Souma 0.3 (alpha)

### PR DESCRIPTION
**Pull request by cafca**
Todo
- [x] Windows packaging
- [x] Sync Planets 
- [x] Sync Groups
- [x] Auto-update Souma + database

### CODE REVIEW

**Comment by cafca** [comment]
@kahartma @cartisan please confirm that this works for you

**Comment by kahartma** [comment]
Flask-WTF==0.9.4
import flask.ext.wtf works

Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from web_ui import app, db
  File "C:\Users\Greg\Documents\GitHub\souma2\web_ui__init__.py", line 138, in
<module>
    import web_ui.views
  File "C:\Users\Greg\Documents\GitHub\souma2\web_ui\views.py", line 9, in <modu
le>
    from web_ui.forms import *
  File "C:\Users\Greg\Documents\GitHub\souma2\web_ui\forms.py", line 1, in <modu
le>
    from flask.ext.wtf import Form, TextField, SelectField, FileField, HiddenFie
ld,\
  File "C:\PythonSouma\lib\site-packages\flask\exthook.py", line 87, in load_mod
ule
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.wtf.TextField

**Comment by cafca** [comment]
If the Windows packaging is working I would like to test Souma on a couple of different setups to see whether there are incompatibilities with different OS versions, browsers etc. 

—

**Comment by cafca** [comment]
```
Traceback (most recent call last):
  File "/Users/vahrend/Projects/soumaenv/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/vahrend/Projects/soumaenv/souma/astrolab/helpers.py", line 53, in setup_astrolab
    with open(word_ids_filename, 'wb') as f:
IOError: [Errno 2] No such file or directory: 'static/data/enwiki__wordids.txt'
<Greenlet at 0x107829c30: setup_astrolab> failed with IOError
```

@kahartma When we implement automatic updates, they will work by replacing the complete application directory with a newer version. Because of that, we can't store data like the model data in there - it needs to go into the user data directory (`app.config["USER_DATA"]`)

**Comment by cafca** [comment]
OK, that was too fast. I broke other things now.

**Comment by cafca** [comment]
Should work now.

**Comment by cafca** [comment]
Something is really weird. I think I might have accidentally reset the dev branch to an earlier stage when I undid the commit Kay made to the master branch some days ago. Changes from #170 are gone.

**Comment by cafca** [comment]
I can't find any other missing commits right now, so I will just merge #170 again. If we had not developed in feature branches I would have no way of knowing what is missing.

**Comment by kahartma** [comment]
e-synapse :: electrical [C:\Users\Greg\Documents\GitHub\souma2\synapse\electrica
l.py:295]
GET [] / http://glia.herokuapp.com/v0/ failed.
Param: None
Payload: None
Errors:
- 401 Client Error: UNAUTHORIZED
- Parsing JSON failed: No JSON object could be decoded

e-synapse :: electrical [C:\Users\Greg\Documents\GitHub\souma2\synapse\electrica
l.py:172]
Error connecting to Glia:
401 Client Error: UNAUTHORIZED
- Parsing JSON failed: No JSON object could be decoded

**Pull request merged**
