### PR TITLE
Reflection system

### PR DESCRIPTION
**Pull request by cafca**
- Digital diary
  - View: Create a diary entry
  - View: View an existing entry
    - Contains entry, TextQuestions for this day, graph of RangeQuetions with current day marked
  - View: Overview for reflection system
    - Contains today's diary entry or a form for entering a new entry
    - Diagrams 
    - Form for activating/deactivating existing catalogues
- Questionnaire
  - Model: Catalogue (name, description, author_id, activated)
    - Can load questions from CSV file
  - Model: Question (text, )
    - RangeQuestion (start_value, end_value)
    - TextQuestion (is_short) 
  - Model: Answer (datetime)
    - RangeAnswer (value)
    - TextAnswer (value)
  - View macro: CRUD for Answer objects

### CODE REVIEW

**Comment by cafca** [comment]
:open_mouth:

**Comment by cartisan** [comment]
Hmm... who did the alembic-branch get here? Oo

**Comment by cafca** [comment]
Uhm.. I will fix it later. Was an accident 

—

**Comment by cafca** [comment]
New pull request is here https://github.com/ciex/souma/pull/181

**Pull request closed without merging**
