### PR TITLE
Auto-update

### PR DESCRIPTION
**Pull request by cafca**
Auto-update using Esky wrapper around py2app, py2exe.
- Souma checks for updates during startup and every 15 minutes, downloads them and applies at next restart.
- Update list is fetched from Github Wiki.

Changes:
- Startup is no longer prevented if the database is outdated to allow for testing.
- Version identifier must be in `major.minor.patch` format, no appendixes (e.g. `-alpha.1`).
- Startup is much quicker now, since Synapses are only initialized after web_ui is started

### CODE REVIEW

**Comment by cafca** [comment]
@cartisan I merged the Alembic branch here and created a stub at `nucleus.database.initialize_database`. Can you make it work? :monkey_face:

**Comment by cartisan** [comment]
Is noted ( #191 ), right now the study report + semantics is kind off getting at me.
Can you provide some more detail? Make Esky update work with alembic migrations? A quick google revealed exactly 0 relevant results. Oo

**Comment by cafca** [comment]
Haha :D Yes, that was a vague description. 

The updater automatically replaces the application directory with an updated version. When this happens, the database might be in an outdated state. Hence, during each startup we let Alembic update the database to the most recent revision.

If Souma is run from the command line we update with `python manager.py db upgrade head`. In the packaged state however, we want to use Alembic's Python API for this. I created a method stub for this at `nucleus.database.initialize_database` with a description of what that method should do.

**Comment by cafca** [comment]
We probably want to use the `upgrade` method in Flask-Migrate for this, as that is also what gets called from manager.py.

**Comment by cafca** [comment]
@cartisan I spent hours trying to find out why this crashes Souma without a line of error log when it's packaged and works perfectly when it's not. Then I tried it in Windows and got some very detailed and legible error messages. arghxl. Done for today.

**Comment by cafca** [comment]
Removed automatic database updates again because of problems to get it to work in frozen state. Updates to the application code should work now.

**Pull request closed without merging**
