### PR TITLE
Use app.souma.io instead of modifying /etc/hosts

### PR DESCRIPTION
**Pull request by cafca**
lmeuser suggested 

> I would suggest [...] changing the DNS entry of app.souma.io (or something like that) to 127.0.0.1 and just using that as the app URL.

https://github.com/ciex/souma/issues/178

This pull request implements that change and it works. This probably breaks offline access, though. The upside is that we don't have to touch `/etc/hosts/ anymore, so theoretically no setup routine is necessary.

What do you think?

### CODE REVIEW

**Comment by cartisan** [comment]
I don't think I understood this! Where do we set the DNS of app.souma.io to localhost? On heroku?

This indeed would forward to the local souma client I assume, which is what we want. But how does this break offline access? On offline I imagine us using the network address of the local glia instead of app.souma.io, this forwards to localhost and we get what we wanted again?

**Comment by cafca** [comment]
> I don't think I understood this! Where do we set the DNS of app.souma.io to localhost? On heroku?

Heroku is not involved in this. The DNS entry for souma.io looks a bit like this:

souma.io => redirects to blog.souma.io
blog.souma.io => Tumblr
app.souma.io => localhost

It breaks offline access, because your computer can't lookup the DNS entry for app.souma.io without a live connection, and I don't think DNS caching works in this case.

**Comment by cartisan** [comment]
Offline access is for developers only, so there we might go with manually modifyig the hosts-file. For the rest I think the above is ok.

Sidequestion out of curiosity:
Where do we actually set the DNS entry if not on heroku? Oo

**Comment by cafca** [comment]
The DNS servers are from gandi.net where I also bought the domain.

I am not really satisfied with this, though. Offline access is a really cool thing and I want it, we should keep in mind that this needs a better fix.

**Comment by cartisan** [comment]
How about an "options" menu, where people can enable offline access? Upon activation this would execute our well known hosts.py script after appropriately asking for root access. If I'm not mistaken we have to perform the changing of the hosts-file only once?

**Pull request closed without merging**
