### PR TITLE
Packaging

### PR DESCRIPTION
**Pull request by cafca**
All requirements replaced with latest versions, I have not checked
which incompatibilities, etc. are introduced with this yet (except for
those in web_ui/forms.py)

setup.py is not working yet.

http://pythonhosted.org/py2app/tutorial.html

### CODE REVIEW

**Comment by cafca** [comment]
I now put the `setup.py` outside the git repository, because that's apparently what setuptools expects. Not sure whether that's 100% correct, though. So it's not in the repository. huh. Next step is to see whether requirements are correctly included in the packaging.

**Comment by cafca** [comment]
Thought a bit more about it. `setup.py` needs to be outside the repo if `souma` is a module. We thought `souma` should be a module so that the server can import it tp then use the `Vesicle` class etc. Actually, `Vesicle` is in `nucleus` so the server should import that. I don't think we need to make `souma` itself a module.

Confusing! Anyway, I think this is the easier way to do it.

**Comment by cafca** [comment]
Compiling with `py2app` was quite difficult, especially because of gevent and sklearn. Some important things:

https://github.com/Homebrew/homebrew/issues/4750
- This helps resetting the OS X Python environment to a half-way-to-sane state
- `brew doctor` !
- `sudo chown -R $USER /Library/Ruby /Library/Perl /Library/Python`
- `brew remove pip` (1)
- `brew remove distribute` (2)
- `brew remove python` (3)
- `brew cleanup`
- `brew prune`
- Install all 3 of the above in reverse order

Other things:
- Install XCode command line utilities
- `brew install gfortran`

**Specifically for the `setup.py`:**
- Dynamic imports through `__import__()` are not automatically recognized by py2app and need to be added to the py2app options dict > `includes`

**Comment by cafca** [comment]
"Is it possible to deploy/distribute Flask as an executable for desktop use? "

http://www.reddit.com/r/Python/comments/21evjn/is_it_possible_to_deploydistribute_flask_as_an/

**Comment by cafca** [comment]
Packaging works on OS X

**Comment by Trami** [comment]
yeeehhhhh !!! :dancer:

**Comment by cafca** [comment]
Oops .. pull requests can't be merged more than one time. I will create a new pull request for Windows and Linux packaging.

**Pull request merged**
